### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ikeyasu** [skirino/slides#1]
https://github.com/skirino/slides/blob/master/docs/advice_for_new_graduates.html
を来年は別の人が話すことになりそうな気がしますので、ライセンスを確認しておきたいです。

ライセンスは以下で良いでしょうか（MIT）

https://github.com/skirino/slides/blob/master/docs/LICENSE

**Comment by skirino** [comment]
ご指摘ありがとうございます!
MIT licenseにしておきました。
https://github.com/skirino/slides/blob/master/LICENSE
